{
  "formatVersion": "1.1",
  "component": {
    "group": "gamengine",
    "module": "lib",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lib-1.0.jar",
          "url": "lib-1.0.jar",
          "size": 11479,
          "sha512": "2ffcbf613e5f4fde730a9f86c29da20f62e2538209b1de47657e53b85a6f2bb6d7240094d8aa76047fa60b422a48070d4967749fbc61dd867ea90c1c926163bd",
          "sha256": "6013b5aa5dd5ad74deb02e10fcdb4d59390287045f1ce24ed764e35b8d212fb1",
          "sha1": "9be92a0a8f85e840b7ccc654c96ee89d2a1e9282",
          "md5": "b2ff53bc3fb66afea69799edae2a66a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 19,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "lib-1.0.jar",
          "url": "lib-1.0.jar",
          "size": 11479,
          "sha512": "2ffcbf613e5f4fde730a9f86c29da20f62e2538209b1de47657e53b85a6f2bb6d7240094d8aa76047fa60b422a48070d4967749fbc61dd867ea90c1c926163bd",
          "sha256": "6013b5aa5dd5ad74deb02e10fcdb4d59390287045f1ce24ed764e35b8d212fb1",
          "sha1": "9be92a0a8f85e840b7ccc654c96ee89d2a1e9282",
          "md5": "b2ff53bc3fb66afea69799edae2a66a4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lib-1.0-javadoc.jar",
          "url": "lib-1.0-javadoc.jar",
          "size": 124782,
          "sha512": "d2aa6b32a60326526863401e46adef532ee1b57ff18ca9549e53eef5a04b75a07ba94d8f2ae957496ccbe7353afe5b92072136845e14b2209bee300b236ae601",
          "sha256": "99e988e674bc96d65ca20eef1e177c4e124fcf3e994d4af4e0634a6cd595e164",
          "sha1": "bc653f12d2e376bef42db86bdadd5b84f6ce25c7",
          "md5": "ba2818976c8741a65d19c9c24de53ee2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lib-1.0-sources.jar",
          "url": "lib-1.0-sources.jar",
          "size": 8509,
          "sha512": "dc7cedc482235edbd204c2f4e0cba75b079159e408a259c5105369cb52d457de60c25e599dcfcc64eb3e87a792e15f77e01eb45b0636798218da04302af2dd54",
          "sha256": "f0851f4d1559614a1411f39fe7932e09bddab79b3922838722d1a5061e86aaca",
          "sha1": "5eb865a8db58aea65504faf4ae0bfb0fc8313950",
          "md5": "0b37761651cad740c29b24719049052b"
        }
      ]
    }
  ]
}
